//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zaschet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookingID { get; set; }
        public string guestid { get; set; }
        public string roomid { get; set; }
        public Nullable<System.DateTime> checkin { get; set; }
        public Nullable<System.DateTime> checkout { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Book Book1 { get; set; }
        public virtual Book Book2 { get; set; }
    }
}
