//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zaschet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int Guestid { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public Nullable<int> age { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
