//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zaschet
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public int idroom { get; set; }
        public Nullable<int> komnats { get; set; }
        public string size { get; set; }
    }
}
